version: 2

build:
  os: ubuntu-22.04

python:
  version: 3.12
  install:
    - pip install sphinx_rtd_theme
    - pip install recommonmark
  system_packages: true

apt_packages:
  - python3-distutils