version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - make html
    - echo "Сборка завершена"

python:
  version: 3.12
  install:
    - pip install sphinx_rtd_theme
    - pip install recommonmark
  system_packages: true

apt_packages:
  - python3-distutils